### ISSUE TITLE
compile error on OSX 'failed to run custom build'

### ISSUE THREAD

**Issue by julama** [boncheolgu/tflite-rs#17]
When running the following command in OSX:

 `cargo run --example minimal` 

results in this error:

`compiling tflite v0.6.2 (/tflite-rs-master)
error: failed to run custom build command for `tflite v0.6.2 (/tflite-rs-master)`

Caused by:
  process didn't exit successfully: `/tflite-rs-master/target/debug/build/tflite-a28825321d36266c/build-script-build` (exit code: 101)
--- stdout
cargo:warning=couldn't execute `llvm-config --prefix` (error: No such file or directory (os error 2))
cargo:warning=set the LLVM_CONFIG_PATH environment variable to a valid `llvm-config` executable
--- stderr
/bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `dirname /Users/julianamacker/Dropbox (Walkingframes)/Virtual-Mind/brainsea/Enigma prototype/tflite-rs-master/target/debug/build/tflite-312c3a5ce195b601/out/tensorflow/tensorflow-1.13.2/tensorflow/lite/tools/make/Makefile'
mkdir: /gen/macos_x86_64/obj/tensorflow/lite/: Permission denied
make: mkdir: /gen/macos_x86_64/obj/tensorflow/lite/: Permission denied
*** [/gen/macos_x86_64/obj/tensorflow/lite/allocation.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [/gen/macos_x86_64/obj/tensorflow/lite/arena_planner.o] Error 1
mkdir: /gen/macos_x86_64/obj/tensorflow/lite/c/: Permission denied
make: *** [/gen/macos_x86_64/obj/tensorflow/lite/c/c_api_internal.o] Error 1
mkdir: /gen/macos_x86_64/obj/tensorflow/lite/core/api/: Permission denied
make: *** [/gen/macos_x86_64/obj/tensorflow/lite/core/api/error_reporter.o] Error 1
thread 'main' panicked at 'Unable to copy libtensorflow-lite.a to OUT_DIR: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:999:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.`

**Comment by tylerhawkes** [comment]
I just tried this with the code that fixes #18 and I didn't get the error. Can you give more information about the environment or if you're still getting the error?

**Comment by tallamjr** [comment]
Hello, I too seem to be getting perhaps not the same error, but an error nonetheless when I try to run the minimal build:
```
$ cargo clean --verbose && cargo run --example minimal
    Removing /Users/tallamjr/github/EDGE22/forks/tflite-rs/target
   Compiling memchr v2.3.3
   Compiling proc-macro2 v1.0.24
   Compiling unicode-xid v0.2.1
   Compiling syn v1.0.44
   Compiling libc v0.2.79
   Compiling lazy_static v1.4.0
   Compiling cfg-if v0.1.10
   Compiling glob v0.3.0
   Compiling version_check v0.9.2
   Compiling regex-syntax v0.6.19
   Compiling log v0.4.11
   Compiling bitflags v1.2.1
   Compiling quick-error v1.2.3
   Compiling unicode-width v0.1.8
   Compiling bindgen v0.55.1
   Compiling vec_map v0.8.2
   Compiling strsim v0.8.0
   Compiling byteorder v1.3.4
   Compiling termcolor v1.1.0
   Compiling ansi_term v0.11.0
   Compiling if_rust_version v1.0.0
   Compiling lazycell v1.3.0
   Compiling rustc-hash v1.1.0
   Compiling cc v1.0.61
   Compiling peeking_take_while v0.1.2
   Compiling shlex v0.1.1
   Compiling fs_extra v1.2.0
   Compiling maybe-owned v0.3.4
   Compiling libloading v0.6.4
   Compiling thread_local v1.0.1
   Compiling nom v5.1.2
   Compiling humantime v1.3.0
   Compiling textwrap v0.11.0
   Compiling clang-sys v1.0.1
   Compiling aho-corasick v0.7.14
   Compiling atty v0.2.14
   Compiling which v3.1.1
   Compiling quote v1.0.7
   Compiling clap v2.33.3
   Compiling regex v1.4.0
   Compiling cexpr v0.4.0
   Compiling env_logger v0.7.1
   Compiling cpp_common v0.5.5
   Compiling cpp_build v0.5.5
   Compiling thiserror-impl v1.0.21
   Compiling cpp_macros v0.5.5
   Compiling thiserror v1.0.21
   Compiling cpp v0.5.5
   Compiling tflite v0.9.2 (/Users/tallamjr/github/EDGE22/forks/tflite-rs)
error: failed to run custom build command for `tflite v0.9.2 (/Users/tallamjr/github/EDGE22/forks/tflite-rs)`

Caused by:
  process didn't exit successfully: `/Users/tallamjr/github/EDGE22/forks/tflite-rs/target/debug/build/tflite-4692c9baadd078dc/build-script-build` (exit code: 101)
  --- stderr
  /Users/tallamjr/github/EDGE22/forks/tflite-rs/submodules/tensorflow/tensorflow/lite/schema/schema_generated.h:2597:8: error: ISO C++ forbids forward references to 'enum' types
  /Users/tallamjr/github/EDGE22/forks/tflite-rs/submodules/tensorflow/tensorflow/lite/schema/schema_generated.h:2597:32: error: field has incomplete type 'enum FlatBuffersVTableOffset'
  /Users/tallamjr/github/EDGE22/forks/tflite-rs/submodules/tensorflow/tensorflow/lite/schema/schema_generated.h:2597:8: note: forward declaration of 'tflite::FlatBuffersVTableOffset'
  /Users/tallamjr/github/EDGE22/forks/tflite-rs/submodules/tensorflow/tensorflow/lite/schema/schema_generated.h:2601:61: error: use of undeclared identifier 'VT_CUSTOM'
  /Users/tallamjr/github/EDGE22/forks/tflite-rs/submodules/tensorflow/tensorflow/lite/schema/schema_generated.h:2604:12: error: cannot initialize object parameter of type 'const flatbuffers::Table' with an expression of type 'const tflite::CustomQuantization'
  /Users/tallamjr/github/EDGE22/forks/tflite-rs/submodules/tensorflow/tensorflow/lite/schema/schema_generated.h:2605:35: error: use of undeclared identifier 'VT_CUSTOM'
  /Users/tallamjr/github/EDGE22/forks/tflite-rs/submodules/tensorflow/tensorflow/lite/schema/schema_generated.h:2618:40: error: no member named 'VT_CUSTOM' in 'tflite::CustomQuantization'
  /Users/tallamjr/github/EDGE22/forks/tflite-rs/submodules/tensorflow/tensorflow/lite/schema/schema_generated.h:2666:32: error: field has incomplete type 'enum FlatBuffersVTableOffset'
  /Users/tallamjr/github/EDGE22/forks/tflite-rs/submodules/tensorflow/tensorflow/lite/schema/schema_generated.h:2597:8: note: forward declaration of 'tflite::FlatBuffersVTableOffset'
  /Users/tallamjr/github/EDGE22/forks/tflite-rs/submodules/tensorflow/tensorflow/lite/schema/schema_generated.h:2676:59: error: use of undeclared identifier 'VT_MIN'
  /Users/tallamjr/github/EDGE22/forks/tflite-rs/submodules/tensorflow/tensorflow/lite/schema/schema_generated.h:2679:59: error: use of undeclared identifier 'VT_MAX'
  /Users/tallamjr/github/EDGE22/forks/tflite-rs/submodules/tensorflow/tensorflow/lite/schema/schema_generated.h:2682:59: error: use of undeclared identifier 'VT_SCALE'
  /Users/tallamjr/github/EDGE22/forks/tflite-rs/submodules/tensorflow/tensorflow/lite/schema/schema_generated.h:2685:61: error: use of undeclared identifier 'VT_ZERO_POINT'
  /Users/tallamjr/github/EDGE22/forks/tflite-rs/submodules/tensorflow/tensorflow/lite/schema/schema_generated.h:2688:63: error: use of undeclared identifier 'VT_DETAILS_TYPE'
  /Users/tallamjr/github/EDGE22/forks/tflite-rs/submodules/tensorflow/tensorflow/lite/schema/schema_generated.h:2691:37: error: use of undeclared identifier 'VT_DETAILS'
  /Users/tallamjr/github/EDGE22/forks/tflite-rs/submodules/tensorflow/tensorflow/lite/schema/schema_generated.h:2698:30: error: use of undeclared identifier 'VT_QUANTIZED_DIMENSION'
  /Users/tallamjr/github/EDGE22/forks/tflite-rs/submodules/tensorflow/tensorflow/lite/schema/schema_generated.h:2701:12: error: cannot initialize object parameter of type 'const flatbuffers::Table' with an expression of type 'const tflite::QuantizationParameters'
  /Users/tallamjr/github/EDGE22/forks/tflite-rs/submodules/tensorflow/tensorflow/lite/schema/schema_generated.h:2702:35: error: use of undeclared identifier 'VT_MIN'
  /Users/tallamjr/github/EDGE22/forks/tflite-rs/submodules/tensorflow/tensorflow/lite/schema/schema_generated.h:2704:35: error: use of undeclared identifier 'VT_MAX'
  /Users/tallamjr/github/EDGE22/forks/tflite-rs/submodules/tensorflow/tensorflow/lite/schema/schema_generated.h:2706:35: error: use of undeclared identifier 'VT_SCALE'
  /Users/tallamjr/github/EDGE22/forks/tflite-rs/submodules/tensorflow/tensorflow/lite/schema/schema_generated.h:2708:35: error: use of undeclared identifier 'VT_ZERO_POINT'
  fatal error: too many errors emitted, stopping now [-ferror-limit=]
  /Users/tallamjr/github/EDGE22/forks/tflite-rs/submodules/tensorflow/tensorflow/lite/schema/schema_generated.h:2597:8: error: ISO C++ forbids forward references to 'enum' types, err: true
  /Users/tallamjr/github/EDGE22/forks/tflite-rs/submodules/tensorflow/tensorflow/lite/schema/schema_generated.h:2597:32: error: field has incomplete type 'enum FlatBuffersVTableOffset', err: true
  /Users/tallamjr/github/EDGE22/forks/tflite-rs/submodules/tensorflow/tensorflow/lite/schema/schema_generated.h:2601:61: error: use of undeclared identifier 'VT_CUSTOM', err: true
  /Users/tallamjr/github/EDGE22/forks/tflite-rs/submodules/tensorflow/tensorflow/lite/schema/schema_generated.h:2604:12: error: cannot initialize object parameter of type 'const flatbuffers::Table' with an expression of type 'const tflite::CustomQuantization', err: true
  /Users/tallamjr/github/EDGE22/forks/tflite-rs/submodules/tensorflow/tensorflow/lite/schema/schema_generated.h:2605:35: error: use of undeclared identifier 'VT_CUSTOM', err: true
  /Users/tallamjr/github/EDGE22/forks/tflite-rs/submodules/tensorflow/tensorflow/lite/schema/schema_generated.h:2618:40: error: no member named 'VT_CUSTOM' in 'tflite::CustomQuantization', err: true
  /Users/tallamjr/github/EDGE22/forks/tflite-rs/submodules/tensorflow/tensorflow/lite/schema/schema_generated.h:2666:32: error: field has incomplete type 'enum FlatBuffersVTableOffset', err: true
  /Users/tallamjr/github/EDGE22/forks/tflite-rs/submodules/tensorflow/tensorflow/lite/schema/schema_generated.h:2676:59: error: use of undeclared identifier 'VT_MIN', err: true
  /Users/tallamjr/github/EDGE22/forks/tflite-rs/submodules/tensorflow/tensorflow/lite/schema/schema_generated.h:2679:59: error: use of undeclared identifier 'VT_MAX', err: true
  /Users/tallamjr/github/EDGE22/forks/tflite-rs/submodules/tensorflow/tensorflow/lite/schema/schema_generated.h:2682:59: error: use of undeclared identifier 'VT_SCALE', err: true
  /Users/tallamjr/github/EDGE22/forks/tflite-rs/submodules/tensorflow/tensorflow/lite/schema/schema_generated.h:2685:61: error: use of undeclared identifier 'VT_ZERO_POINT', err: true
  /Users/tallamjr/github/EDGE22/forks/tflite-rs/submodules/tensorflow/tensorflow/lite/schema/schema_generated.h:2688:63: error: use of undeclared identifier 'VT_DETAILS_TYPE', err: true
  /Users/tallamjr/github/EDGE22/forks/tflite-rs/submodules/tensorflow/tensorflow/lite/schema/schema_generated.h:2691:37: error: use of undeclared identifier 'VT_DETAILS', err: true
  /Users/tallamjr/github/EDGE22/forks/tflite-rs/submodules/tensorflow/tensorflow/lite/schema/schema_generated.h:2698:30: error: use of undeclared identifier 'VT_QUANTIZED_DIMENSION', err: true
  /Users/tallamjr/github/EDGE22/forks/tflite-rs/submodules/tensorflow/tensorflow/lite/schema/schema_generated.h:2701:12: error: cannot initialize object parameter of type 'const flatbuffers::Table' with an expression of type 'const tflite::QuantizationParameters', err: true
  /Users/tallamjr/github/EDGE22/forks/tflite-rs/submodules/tensorflow/tensorflow/lite/schema/schema_generated.h:2702:35: error: use of undeclared identifier 'VT_MIN', err: true
  /Users/tallamjr/github/EDGE22/forks/tflite-rs/submodules/tensorflow/tensorflow/lite/schema/schema_generated.h:2704:35: error: use of undeclared identifier 'VT_MAX', err: true
  /Users/tallamjr/github/EDGE22/forks/tflite-rs/submodules/tensorflow/tensorflow/lite/schema/schema_generated.h:2706:35: error: use of undeclared identifier 'VT_SCALE', err: true
  /Users/tallamjr/github/EDGE22/forks/tflite-rs/submodules/tensorflow/tensorflow/lite/schema/schema_generated.h:2708:35: error: use of undeclared identifier 'VT_ZERO_POINT', err: true
  fatal error: too many errors emitted, stopping now [-ferror-limit=], err: true
  thread 'main' panicked at 'Unable to generate bindings: ()', build.rs:233:40
  stack backtrace:
     0:        0x10e107bb4 - std::backtrace_rs::backtrace::libunwind::trace::h8370c94edb707056
                                 at /rustc/aa30bf3442be752e9f8dc9ff7fe70c258d41ac6b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
     1:        0x10e107bb4 - std::backtrace_rs::backtrace::trace_unsynchronized::hcf3c5408e591933a
                                 at /rustc/aa30bf3442be752e9f8dc9ff7fe70c258d41ac6b/library/std/src/../../backtrace/src/backtrace/mod.rs:66
     2:        0x10e107bb4 - std::sys_common::backtrace::_print_fmt::he4674edaf825d287
                                 at /rustc/aa30bf3442be752e9f8dc9ff7fe70c258d41ac6b/library/std/src/sys_common/backtrace.rs:79
     3:        0x10e107bb4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1c5ef320eed555e7
                                 at /rustc/aa30bf3442be752e9f8dc9ff7fe70c258d41ac6b/library/std/src/sys_common/backtrace.rs:58
     4:        0x10e12dc40 - core::fmt::write::h2b6b26787fc391c2
                                 at /rustc/aa30bf3442be752e9f8dc9ff7fe70c258d41ac6b/library/core/src/fmt/mod.rs:1082
     5:        0x10e10376b - std::io::Write::write_fmt::h68041ee9ba1eefee
                                 at /rustc/aa30bf3442be752e9f8dc9ff7fe70c258d41ac6b/library/std/src/io/mod.rs:1514
     6:        0x10e10b955 - std::sys_common::backtrace::_print::h440f4958e081f943
                                 at /rustc/aa30bf3442be752e9f8dc9ff7fe70c258d41ac6b/library/std/src/sys_common/backtrace.rs:61
     7:        0x10e10b955 - std::sys_common::backtrace::print::h851fb5cbd9821ad7
                                 at /rustc/aa30bf3442be752e9f8dc9ff7fe70c258d41ac6b/library/std/src/sys_common/backtrace.rs:48
     8:        0x10e10b955 - std::panicking::default_hook::{{closure}}::hb5a855fc6c1c039c
                                 at /rustc/aa30bf3442be752e9f8dc9ff7fe70c258d41ac6b/library/std/src/panicking.rs:200
     9:        0x10e10b697 - std::panicking::default_hook::h60ef5ed5aa9af653
                                 at /rustc/aa30bf3442be752e9f8dc9ff7fe70c258d41ac6b/library/std/src/panicking.rs:219
    10:        0x10e10bf1d - std::panicking::rust_panic_with_hook::hc6b5b181151bed69
                                 at /rustc/aa30bf3442be752e9f8dc9ff7fe70c258d41ac6b/library/std/src/panicking.rs:573
    11:        0x10e10ba8b - std::panicking::begin_panic_handler::{{closure}}::he75e47e8aa4a8d5f
                                 at /rustc/aa30bf3442be752e9f8dc9ff7fe70c258d41ac6b/library/std/src/panicking.rs:476
    12:        0x10e107ff8 - std::sys_common::backtrace::__rust_end_short_backtrace::h4a82ed9b4d6a09d0
                                 at /rustc/aa30bf3442be752e9f8dc9ff7fe70c258d41ac6b/library/std/src/sys_common/backtrace.rs:153
    13:        0x10e10ba4a - rust_begin_unwind
                                 at /rustc/aa30bf3442be752e9f8dc9ff7fe70c258d41ac6b/library/std/src/panicking.rs:475
    14:        0x10e13b8bf - core::panicking::panic_fmt::h657767d6fdf0ce87
                                 at /rustc/aa30bf3442be752e9f8dc9ff7fe70c258d41ac6b/library/core/src/panicking.rs:85
    15:        0x10e13b7c5 - core::option::expect_none_failed::h732ee92e3014c57e
                                 at /rustc/aa30bf3442be752e9f8dc9ff7fe70c258d41ac6b/library/core/src/option.rs:1221
    16:        0x10d99a22e - core::result::Result<T,E>::expect::ha646eb4cbd224926
                                 at /Users/tallamjr/.rustup/toolchains/beta-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/result.rs:933
    17:        0x10d99dd55 - build_script_build::import_tflite_types::h00638790ac601f5e
                                 at /Users/tallamjr/github/EDGE22/forks/tflite-rs/build.rs:233
    18:        0x10d99e50e - build_script_build::main::h431b09015f0a3c34
                                 at /Users/tallamjr/github/EDGE22/forks/tflite-rs/build.rs:512
    19:        0x10d998b4e - core::ops::function::FnOnce::call_once::hbd6f355aab596137
                                 at /Users/tallamjr/.rustup/toolchains/beta-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:227
    20:        0x10d99aad1 - std::sys_common::backtrace::__rust_begin_short_backtrace::h44f25ff5725ac106
                                 at /Users/tallamjr/.rustup/toolchains/beta-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:137
    21:        0x10d99e884 - std::rt::lang_start::{{closure}}::h37e77007a9b14609
                                 at /Users/tallamjr/.rustup/toolchains/beta-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/rt.rs:66
    22:        0x10e10c290 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hdc21b78200d5ae9a
                                 at /rustc/aa30bf3442be752e9f8dc9ff7fe70c258d41ac6b/library/core/src/ops/function.rs:259
    23:        0x10e10c290 - std::panicking::try::do_call::hb88f1c4543f1ef85
                                 at /rustc/aa30bf3442be752e9f8dc9ff7fe70c258d41ac6b/library/std/src/panicking.rs:373
    24:        0x10e10c290 - std::panicking::try::h64fbebf898ffc91d
                                 at /rustc/aa30bf3442be752e9f8dc9ff7fe70c258d41ac6b/library/std/src/panicking.rs:337
    25:        0x10e10c290 - std::panic::catch_unwind::he1cd28a9fddd6b97
                                 at /rustc/aa30bf3442be752e9f8dc9ff7fe70c258d41ac6b/library/std/src/panic.rs:379
    26:        0x10e10c290 - std::rt::lang_start_internal::h99a094cfad413899
                                 at /rustc/aa30bf3442be752e9f8dc9ff7fe70c258d41ac6b/library/std/src/rt.rs:51
    27:        0x10d99e861 - std::rt::lang_start::h10b6fea0bb412d59
                                 at /Users/tallamjr/.rustup/toolchains/beta-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/rt.rs:65
    28:        0x10d99e542 - _main
```
This also seems to be the same error/output I get when running `cargo build --verbose` too.

Please do let me know if there is further information that would be handy, apologies, I am very new to this project and `rust` in general so not sure if I have missed something obvious.
