### ISSUE TITLE
Unable to build 0.6.3 on linux

### ISSUE THREAD

**Issue by tylerhawkes** [boncheolgu/tflite-rs#18]
I just upgraded to the latest (I tried it when 0.6 was first released and got a build error and just reverted for the time being). I got the following:

error: failed to run custom build command for `tflite v0.6.3`

Caused by:
  process didn't exit successfully: `/target/debug/build/tflite-fe3dac74f1fccc3f/build-script-build` (exit code: 101)
--- stdout
cargo:warning=couldn't execute `llvm-config --prefix` (error: No such file or directory (os error 2))
cargo:warning=set the LLVM_CONFIG_PATH environment variable to a valid `llvm-config` executable

--- stderr
/usr/bin/../lib/gcc/x86_64-redhat-linux/9/../../../../include/c++/9/memory:121:25: error: cast from pointer to smaller type 'uintptr_t' (aka 'unsigned int') loses information
/usr/bin/../lib/gcc/x86_64-redhat-linux/9/../../../../include/c++/9/memory:121:25: error: cast from pointer to smaller type 'uintptr_t' (aka 'unsigned int') loses information, err: true
thread 'main' panicked at 'Unable to generate STL bindings: ()', src/libcore/result.rs:1084:5
stack backtrace:
   0:     0x5644f8489f6b - backtrace::backtrace::libunwind::trace::h89fcc71e59e3bc5b
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/libunwind.rs:88
   1:     0x5644f8489f6b - backtrace::backtrace::trace_unsynchronized::h0bad9be1379e729a
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/mod.rs:66
   2:     0x5644f8489f6b - std::sys_common::backtrace::_print::hd3382a1f33c473da
                               at src/libstd/sys_common/backtrace.rs:47
   3:     0x5644f8489f6b - std::sys_common::backtrace::print::h0ec6f03cfb8e76a6
                               at src/libstd/sys_common/backtrace.rs:36
   4:     0x5644f8489f6b - std::panicking::default_hook::{{closure}}::h96cbf7b454e3f557
                               at src/libstd/panicking.rs:200
   5:     0x5644f8489c46 - std::panicking::default_hook::h95a8f00337383d83
                               at src/libstd/panicking.rs:214
   6:     0x5644f848a6dd - std::panicking::rust_panic_with_hook::h92f98b46e22f14ed
                               at src/libstd/panicking.rs:477
   7:     0x5644f848a262 - std::panicking::continue_panic_fmt::h25abfbb4e5b7043a
                               at src/libstd/panicking.rs:384
   8:     0x5644f848a146 - rust_begin_unwind
                               at src/libstd/panicking.rs:311
   9:     0x5644f84acf4d - core::panicking::panic_fmt::h7e9f94035af782b3
                               at src/libcore/panicking.rs:85
  10:     0x5644f84ad047 - core::result::unwrap_failed::hf7591c1dd9412006
                               at src/libcore/result.rs:1084
  11:     0x5644f7dc0941 - core::result::Result<T,E>::expect::h95f9a79adaa44083
                               at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libcore/result.rs:879
  12:     0x5644f7dc3fa1 - build_script_build::import_stl_types::h1c2a9dba812ec57c
                               at /rust/cargo/registry/src/github.com-1ecc6299db9ec823/tflite-0.6.3/build.rs:261
  13:     0x5644f7dc40ba - build_script_build::main::h95b9cf054ee99db6
                               at /rust/cargo/registry/src/github.com-1ecc6299db9ec823/tflite-0.6.3/build.rs:513
  14:     0x5644f7dd4ff3 - std::rt::lang_start::{{closure}}::h0c7f757304ff61f9
                               at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/rt.rs:64
  15:     0x5644f848a0e3 - std::rt::lang_start_internal::{{closure}}::h4e93c1949c7a1955
                               at src/libstd/rt.rs:49
  16:     0x5644f848a0e3 - std::panicking::try::do_call::h9440ccd4dc467eaa
                               at src/libstd/panicking.rs:296
  17:     0x5644f849473a - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:80
  18:     0x5644f848acad - std::panicking::try::hc046e7ee42ee744f
                               at src/libstd/panicking.rs:275
  19:     0x5644f848acad - std::panic::catch_unwind::h27dfc457c200aee0
                               at src/libstd/panic.rs:394
  20:     0x5644f848acad - std::rt::lang_start_internal::hea1b49a567afe309
                               at src/libstd/rt.rs:48
  21:     0x5644f7dd4feb - std::rt::lang_start::h230272963a6d05aa
                               at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/rt.rs:64
  22:     0x7f7c6c3cdf33 - __libc_start_main
  23:     0x5644f7dbd23e - _start
  24:                0x0 - <unknown>

I've run into this before in other projects and it seems like we just need to add some other flags to the compiler invocation.

**Comment by tylerhawkes** [comment]
I should add that I'm cross-compiling to `aarch64-unknown-linux-gnu`.
